filebeat:
    prospectors:
        -
            paths:
            - /thlogs/*/log/*_output.json
            input_type: log
output:
    elasticsearch:
        hosts: ["elasticsearch:9200"]
        template:
            path: "filebeat.template.json"
